### ISSUE TITLE
needs permission to access the user directory

### ISSUE THREAD

**Issue by maeknight** [flathub/com.behringer.XAirEdit#11]
x air tries to save it's settings to `~/.config/X-Air-Edit` but it doesn't have permission to access that directory so it's always in the default state on startup, this is causing issues such as #10.

i fixed this by editing the flatpak in flatseal and enabling the 'all usr files' option. i need this enabled anyway since i want to be able to save and load presets from my home folder.

**Comment by scy** [comment]
> x air tries to save it's settings to `~/.config/X-Air-Edit`

For future reference, in case anyone else ends up here: The path is actually `~/.config/.X-AIR-Edit`, with a leading dot in the subdirectory, and more capital letters.
