### ISSUE TITLE
popup menues no longer work

### ISSUE THREAD

**Issue by maeknight** [flathub/com.behringer.XAirEdit#16]
i tested the new 1.8 release and the popup menues no longer work:

[Screencast from 2023-09-13 08-05-49.webm](https://github.com/flathub/com.behringer.XAirEdit/assets/130556032/001e9e2c-c3b0-4378-b9bc-ee4472241fad)

i'm clicking but nothing happens, perhaps it's a wayland problem? i'm not sure how to tell.

while 1.7 has some issues for me, this will definitely make the mixer unusable. does anyone know how to report bugs to behringer?

**Comment by maeknight** [comment]
it was this build that i tested:

https://buildbot.flathub.org/#/builders/6/builds/65169

**Comment by maeknight** [comment]
the problem persists with build [65173](https://buildbot.flathub.org/#/builders/6/builds/65173) from #15

**Comment by jmaibaum** [comment]
Does it happen as well if you log into an X11 session?

**Comment by maeknight** [comment]
yeah, it works under x11, how frustrating. still needs reporting upstream.

**Comment by jmaibaum** [comment]
Searching a little bit, I think getting in touch with Behringer works mainly via https://community.musictribe.com/

**Comment by maeknight** [comment]
closing this as it now works perfectly every time, i have no idea what changed but it could be anything
