### ISSUE TITLE
64bit arm raspi version?

### ISSUE THREAD

**Issue by oh5lep** [flathub/com.behringer.XAirEdit#17]
Just updated raspi to bookworm 64bit, which seems to be mistake. Anyone aware of X-AIR-Edit 64bit raspi version development?

**Comment by jmaibaum** [comment]
Thank you for your question.

How did you use the flatpak prior to updating to the 64bit version? So far there was no 32bit ARM flatpak either (see #2).

Questions regarding 64bit ARM support for X-AirEdit are best asked to Behringer directly. We only repackage what they are offering as flatpak (and only what we can test ourselves, and arm 32bit is not supported by flathub anymore). I am also not affiliated with Behringer.

**Comment by oh5lep** [comment]
Opened question in Behringer forum.
